import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Poppins, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { TooltipProvider } from "@/components/ui/tooltip"

const jetbrainsMonoJetbrainsMono = JetBrains_Mono({subsets:['latin'],weight:['100','200','300','400','500','600','700','800'],variable:'--font-jetbrains-mono'});

const poppinsPoppins = Poppins({subsets:['latin'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-poppins'});

const openSansOpenSans = Open_Sans({subsets:['latin'],weight:['300','400','500','600','700','800'],variable:'--font-open-sans'});

import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";

const geistGeist = Geist({subsets:['latin'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-geist'});

const geistMonoGeistMono = Geist_Mono({subsets:['latin'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-geist-mono'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html
      lang="en"
      className={cn("h-full dark", "antialiased", geistGeist.variable, geistMonoGeistMono.variable, openSansOpenSans.variable, poppinsPoppins.variable, jetbrainsMonoJetbrainsMono.variable)}
    >
      {/* <body className="min-h-full flex flex-col"><TooltipProvider>{children}</TooltipProvider></body> */}
      <body>
        <SessionProvider session={session}><TooltipProvider>{children}</TooltipProvider></SessionProvider>
      </body>
      {/* <body className="min-h-full flex flex-col">{children}</body> */}
    </html>
  );
}
